# Generated by Django 3.2.7 on 2021-10-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0003_auto_20211004_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
